### ISSUE TITLE
Add Authentication Handling on the Client Side

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#13]
The client currently lacks proper authentication management when interacting with the server. Upon successful login, the server returns an authentication token in cookies, that must be included in Hedar of all API requests. 

1. Handle Login Response:

After the login API call, ensure the token returned in cookies is properly stored and accessible.

2. Include Token in API Requests:

Modify API requests to automatically include the authentication token (e.g., using credentials: 'include' in fetch or axios).

3. Check Authenticated State:

- Add logic to determine if a user is authenticated (e.g., checking for a valid token or session).

- Redirect unauthenticated users to the login page if necessary.

4. Logout Functionality:

Implement a logout function to clear any stored authentication state and redirect the user to the login page.
5. Test All API Calls:

Ensure all relevant endpoints (e.g., fetching quizzes, submitting answers) correctly include the authentication token.

**Comment by RachelCh634** [comment]
I'm interested in trying.

**Comment by ChayaCodes** [comment]
Hi @RachelCh634 ,
That's great! Let me know if you need any clarification or help as you get started. Good luck, and I look forward to seeing your progress! 😊

**Comment by ChayaCodes** [comment]
@RachelCh634 , How it's going?

**Comment by RachelCh634** [comment]
Chaya, I saw that you completed the issue, what I've done so far is receive a token when logging in and registering.
The token is stored in an accessible form in cookies.
What do you want me to add?

**Comment by RachelCh634** [comment]
Are you also interested in the logic of disengagement?
I don't understand what else you expect.
Keep me updated.

**Comment by ChayaCodes** [comment]
yes, we need also develop the logout logic, but I think it's other issue.

**Comment by RachelCh634** [comment]
Okay, so am I done for you?
I'll check if the logout is also suitable for me, maybe you should open a new issue for that anyway.

**Comment by ChayaCodes** [comment]
Great, you can close this issue

**Comment by RachelCh634** [comment]
Closes #13
