### ISSUE TITLE
Redesign and Style the Navigation Menu

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#14]
Redesign the navigation menu to match the site's playful, game-like theme. 
and is fully responsive on all devices.

Notes:
The new design should be visually appealing, consistent with the UI, and accessible.

**Comment by chagitA** [comment]
@ChayaCodes I'm interested in taking this. Is there a design you had in mind or would you like me to take care of that as well?

**Comment by ChayaCodes** [comment]
Hi @chagitA,
There's no specific design prepared yet, so feel free to take the creative lead on this. It would be great if you could first sketch out your ideas in Figma, PowerPoint, or any tool you prefer, and share them here so I can provide feedback before you proceed.

Thank you, and good luck! 😊

**Comment by chagitA** [comment]
I was thinking of a design like this, where the top row is the button and the bottom row is when the button is hovered/pressed.
![navbar design](https://github.com/user-attachments/assets/db9ac8a0-c7f1-4bc1-a31f-b2419109c6de)

I think it would be more correct to associate the account button with the login screen, from where it would be possible to get to registration.
What do you think?

**Comment by ChayaCodes** [comment]
Hi @chagitA,
This looks great! 😊

**Comment by chagitA** [comment]
I have created a Pull Request to address this issue: [https://github.com/ChayaCodes/trivia-quiz/pull/23](url)

**Comment by ChayaCodes** [comment]
It will be great to add a tooltip to all links to clarify the purpose of each button. Something like this!
[image](https://github.com/user-attachments/assets/15ef3393-fb13-4a72-b4ec-35189e4b4d32)

**Comment by ChayaCodes** [comment]
@chagitA  Would you like to take care of this as well?

**Comment by chagitA** [comment]
Sounds reasonable. I'll take care of it.
