### ISSUE TITLE
Replace Edit and Activate Quiz Buttons with Icons and Add Delete Option

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#18]
Improve the quiz interface by replacing the "Edit" and "Activate" text in the buttons with representative icons. Add a "Delete" button with its own icon. Tooltips should appear on hover to describe each button's function.

**Comment by ChayaCodes** [comment]
@zehava-drabkin, Would you be interested in taking this task on?

**Comment by zehava-drabkin** [comment]
Yes, thank you for thinking of me.

**Comment by ChayaCodes** [comment]
Something like that
![image](https://github.com/user-attachments/assets/2e843bd7-ae84-4267-a581-b05868797953)

**Comment by zehava-drabkin** [comment]
Maybe you can post a link because it's blocked for me.

**Comment by zehava-drabkin** [comment]
ok i saw it

**Comment by ChayaCodes** [comment]
@zehava-drabkin , How it's going?

**Comment by ChayaCodes** [comment]
I think you should make the buttons a little smaller.

**Comment by ChayaCodes** [comment]
after that, you can close this issue.

**Comment by zehava-drabkin** [comment]
I accidentally removed the assigned from myself :(

**Comment by ChayaCodes** [comment]
@zehava-drabkin, the tooltip can be separate component, to keep the code DRY.
