### ISSUE TITLE
Merge Client and Server Projects 

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#2]
Enhancement: Merge Client and Server Projects

We need to merge the client-side and server-side projects into a single repository. The following changes are required:

Create two separate directories: server and client.
Organize the server-side files neatly within the server directory.

**Comment by ChayaCodes** [comment]
I have created the client and server directories and moved the server-side files into the server directory. However, we still need to check that everything is working as expected after the changes.

**Comment by ruth7873** [comment]
I want to try to do it.

**Comment by ChayaCodes** [comment]
@ruth7873 Great! Go ahead and give it a try. Let me know if you need any help or clarification. Thanks for taking this on! 😊

**Comment by ChayaCodes** [comment]
Hi @ruth7873,  

Here’s an explanation of the server-side files to help you understand the current structure:  

I originally developed the server as part of a larger project and later copied the relevant files into this repository. Therefore, it’s likely that the code is not fully functional right now, and the file organization still needs improvement.  

Here’s what each file does:  

1. **`admin_interface.py`**  
   - This is the BLL (Business Logic Layer) for the quiz creator interface.  
   - It contains the logic for creating, editing, and managing quizzes.  

2. **`auth.py`**  
   - This is the BLL for authentication, handling login, registration, etc.  

3. **`auth_api.py`**  
   - This is the API layer for authentication.  

4. **`database_functions_quizes.py`**  
   - This is the DAL (Data Access Layer) for the entire system.  
   - It defines the database tables and basic CRUD functions.  

5. **`participant_interface.py`**  
   - This file contains the logic for quiz participation.  
   - Participants can perform two main actions:  
     - Registering their phone number to join a quiz.  
     - Submitting their answers to the current question.  

6. **`quiz_service.py`**  
   - This is the API interface for the telephone-based quiz system, following the system’s examples and guidelines.  

7. **`quizzes_interface_api.py`**  
   - This is the API layer for the web interface used by the quiz creator.  
   - It defines the API endpoints for creating and editing quizzes, etc.  

### Supporting Files:  
8. **`app.py`**  
9. **`blueprints.py`**  
10. **`database_functions.py`**  
11. **`utils.py`**  
   - The telephone interface relies on `utils.py` and `database_functions.py`.  

I hope this breakdown helps! Let me know if you need further clarification or assistance while working on the project.  

Thanks again for taking this on! 😊

**Comment by ChayaCodes** [comment]
What we need is to ensure that everything is well-organized in layers, and to check the APIs to make sure everything is working as expected.

**Comment by ChayaCodes** [comment]
@ruth7873, How's it going?

**Comment by ChayaCodes** [comment]
@ruth7873, you can to move the folders and files to the sever directory, and delete the "quiz_system" folder

**Comment by ChayaCodes** [comment]
@ruth7873, please also update the documentation and update the routes of the installation.

**Comment by ruth7873** [comment]
I see you already do it, and I can`t continue work on it, so maybe assign it to someone else.

**Comment by ChayaCodes** [comment]
Hi @RachelCh634,
Thanks for the update! Does this mean you've completed the task?

**Comment by ChayaCodes** [comment]
@ruth7873 , I think it's completed.
