### ISSUE TITLE
Improve Quiz Creation Page Design and Add Quiz Edit Page 

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#24]
1. Enhance the visual design of the quiz creation page.
2. Refactor the quiz creation page to make it generic and reusable so the same design and component can be used for both creating and editing a quiz.
3. Create the quiz edit page using the new reusable design/component.

**Comment by Tzipif** [comment]
אשמח לקבל את המשימה הזו...

**Comment by ChayaCodes** [comment]
Great, @Tzipif!

good luck!

**Comment by ChayaCodes** [comment]
@Tzipif, I haven't heard from you and I don't know if you're still working on it, so for now I'm marking the issue as unassigned. If you're still working on it, let me know.

**Comment by Tzipif** [comment]
הי חיה,
אני בהחלט עובדת על זה....

*יום שמח,*
*ותמיד שמח!*
-❤️ תיק עבודות שלי? באהבה. <http://tzipisite.co.il/> ❤️-


‫בתאריך יום ו׳, 20 בדצמ׳ 2024 ב-13:18 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChayaCodes** [comment]
Thank you! I’d love to hear an update on your progress with the development whenever you have a chance.

**Comment by ChayaCodes** [comment]
@Tzipif, How it's going?

**Comment by Tzipif** [comment]
בינתיים זה טוב!

*יום שמח,*
*ותמיד שמח!*
-❤️ תיק עבודות שלי? באהבה. <http://tzipisite.co.il/> ❤️-


‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-16:02 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by Tzipif** [comment]
Not finished yet.

*יום שמח,*
*ותמיד שמח!*
-❤️ תיק עבודות שלי? באהבה. <http://tzipisite.co.il/> ❤️-


‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-16:10 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChayaCodes** [comment]
@Tzipif,  Since the deadline for completing this is by this week, it's crucial that we progress quickly.

Please let me know where you are with the task.

**Comment by Tzipif** [comment]
צודקת!
https://github.com/Tzipif/trivia-quiz.git
מתכננת לשבת על זה ממש ברצינות היום ומחר בבוקר...

*יום שמח,*
*ותמיד שמח!*
-❤️ תיק עבודות שלי? באהבה. <http://tzipisite.co.il/> ❤️-


‫בתאריך יום ב׳, 23 בדצמ׳ 2024 ב-11:58 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬
