### ISSUE TITLE
Make the Existing Navigation Bar Responsive

### ISSUE THREAD

**Issue by rivka14** [ChayaCodes/trivia-quiz#29]
The application already has a navigation bar, but it is not responsive. 
Update the navigation bar to ensure it adapts seamlessly to different screen sizes, 
providing an optimal user experience on both desktop and mobile devices.

**Comment by rivka14** [comment]
@ChayaCodes , I would like to work on this issue.
Before starting, I want to confirm the links for the navigation bar. Based on the current design and requirements, the navigation bar will include the following links:

- דף הבית
- התחברות 
- חידונים
- צור חידון 

Can you please confirm if these are correct or if any additional links should be added?
Thank you!"

**Comment by ChayaCodes** [comment]
Yes, this is the links in the side bar.

**Comment by rivka14** [comment]
Ok, I'll work on that.
Is adding design libraries relevant, or could it conflict with other code in the project?

**Comment by ChayaCodes** [comment]
Okay, great!
I prefer to add as few additional libraries to the project as possible, but if necessary, you can add more.

**Comment by ChayaCodes** [comment]
@rivka14, How it's going?

**Comment by rivka14** [comment]
#49

**Comment by ChayaCodes** [comment]
@rivka14, did you see the comment on the pull request about the merge conflicts?

**Comment by ChayaCodes** [comment]
@rivka14, can we close this issue?

**Comment by ChayaCodes** [comment]
The pull caused some issues, so I reverted it. For now, the issue is still open.

**Comment by ChayaCodes** [comment]
Please let me know if you want to continue working on this issue.

**Comment by rivka14** [comment]
@ChayaCodes I’m currently occupied with other projects and won’t be able to address this issue.
