### ISSUE TITLE
option to add nusic/ picture/ moovie question

### ISSUE THREAD

**Issue by estush** [ChayaCodes/trivia-quiz#36]
it's more intresting when we have a couple of question type

**Comment by ChayaCodes** [comment]
I wrote about this in another issue, we can to do that, but add videos and picture require larger datacenter, and I need to check the feasibility. You can develop this feature in a separate branch, and we can decide later whether to include it.

**Comment by ChayaCodes** [comment]
it's duplicate with #37 issue, isn't it?

**Comment by estush** [comment]
yes  it's mistake

‫בתאריך יום ד׳, 18 בדצמ׳ 2024 ב-13:04 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬
