### ISSUE TITLE
option to add nusic/ picture/ moovie question

### ISSUE THREAD

**Issue by estush** [ChayaCodes/trivia-quiz#37]
it's more intresting when we have a couple of question typies

**Comment by ChayaCodes** [comment]
You're absolutely right, having different types of questions makes the quiz more engaging.

Regarding images and videos, implementing them would require a larger data center, so I need to check the feasibility. You can develop this feature in a separate branch, and we can decide later whether to include it.

Additionally, we could consider adding survey questions, which don’t require extra memory.
