### ISSUE TITLE
transition page

### ISSUE THREAD

**Issue by estush** [ChayaCodes/trivia-quiz#38]
give to the user option to do a couple of subject question and before every subject put match image and write the new subject

**Comment by ChayaCodes** [comment]
Hi @estush,
I'm not sure I fully understand which page you're referring to. Could you clarify or provide more details about the transition page and its purpose?

Thanks!

**Comment by estush** [comment]
Sure, for example, if someone wants to create a quiz, the first section
could be about Hanukkah laws, the second section about history, and the
third section about family memories. Before each topic, they can add a
designed page that includes an introduction to the topic, an image, a song,
or just text.

‫בתאריך יום ג׳, 17 בדצמ׳ 2024 ב-19:24 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChayaCodes** [comment]
Understood. That’s a great idea!

**Comment by estush** [comment]
don't do it?

**Comment by ChayaCodes** [comment]
Yes, I closed a number of issues that are planned for future, but their level of urgency is lower, and they are not necessary for running the basic quiz, in order to focus on the urgent tasks.

**Comment by ChayaCodes** [comment]
it's ok? 
you will can to continue this after the basic will be ready.

**Comment by estush** [comment]
OK

‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-16:15 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬
