### ISSUE TITLE
Create a 'User' page

### ISSUE THREAD

**Issue by chagitA** [ChayaCodes/trivia-quiz#53]
When a user logs in, you need to present them with a page that allows them to see their details, and the option to log out.
You need to create a new page that contains the user's name and email and a 'log out' button from the account.
This page will only appear if the user is logged in.

**Comment by ChayaCodes** [comment]
I'm not sure we need a user page. Instead, we can update the navigation bar to display a logout button for logged-in users. Aside from this, we don't have additional user data that would justify having a dedicated user page.
