### ISSUE TITLE
Update requirements file

### ISSUE THREAD

**Issue by chagitA** [ChayaCodes/trivia-quiz#54]
The flask-cors installation must be added to the installation list in the requirements.txt file:
```
...
flask-cors==5.0.0
...
```

**Comment by estush** [comment]
The react-confetti installation must be added to the installation list in the requirements.txt file:

**Comment by ChayaCodes** [comment]
the requirment.txt file is in the server side, and contain only the packages in the server.
the packages in react are in the package.json file.

**Comment by estush** [comment]
oh sorry
thanks for explaining me

‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-14:33 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬
