### ISSUE TITLE
 Player login confirmation with phone number

### ISSUE THREAD

**Issue by estush** [ChayaCodes/trivia-quiz#55]
When the user clicks to connect and log into the game, they should see a confirmation button indicating that their number has been successfully registered.

**Comment by ChayaCodes** [comment]
I think it should be auto navigate to the quizzes page.

**Comment by estush** [comment]
and how would the players know that they're connected?

**Comment by estush** [comment]
@ChayaCodes 
don't do it?

**Comment by ChayaCodes** [comment]
The quizzes page and the create page shouldn't be accessible to users who are not logged in.

**Comment by estush** [comment]
I'll explain what I meant. You know when someone wants to start a game?
They need the players to connect with their phones. How does the user know
if they are connected? They should see their phone number on the screen
before the game starts, or get confirmation that they are in the game on
their phone, regardless of who is connecting the quiz. Do you want each
player to have to register on the website?

‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-15:23 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChayaCodes** [comment]
Ah, okay. 
 think it’s worth changing the title of the issue to avoid confusion.

Additionally, I’ve been considering creating a component for starting the game. This component could display the phone number and quiz ID (for now, a dummy phone number) and provide guidance to participants on how to connect to the game. It could also show a list of connected users.

There’s already an API endpoint:
'/admin/get_participants/<quiz_id>', methods=['GET'])
which returns a list of connected users. You can use this to develop the component.

For now, you can make API requests at consistent intervals, such as every 10 seconds. In the future, we could enhance this with socket functionality.

**Comment by ChayaCodes** [comment]
are you want to take this issue on?

**Comment by estush** [comment]
yes

‫בתאריך יום א׳, 22 בדצמ׳ 2024 ב-15:44 מאת ‪chaya kremer‬‏ <‪
***@***.***‬‏>:‬

**Comment by ChayaCodes** [comment]
great, goo luck! 😊

**Comment by estush** [comment]
![image](https://github.com/user-attachments/assets/b19c5b36-53f1-4b6a-88b2-4d3497b4c368)
![image](https://github.com/user-attachments/assets/76f7d306-a478-450d-a990-9690aab7738d)
what look better?

**Comment by ChayaCodes** [comment]
looks great!
wow!

**Comment by ChayaCodes** [comment]
I don't know what is better

**Comment by estush** [comment]
sooo? what to do? i hate to decide

**Comment by ChayaCodes** [comment]
So the second

**Comment by malka099** [comment]
i worker on this now

**Comment by ChayaCodes** [comment]
perfect, good luck!

**Comment by estush** [comment]
@malka099  what  do you mean? I almost finish?
