### ISSUE TITLE
Develop Component to Display Active Question

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#7]
- Create a React component to display the currently active question in a visually appealing and engaging way.

- The component should show the question text along with the possible answers in a user-friendly and interactive format.

- Add buttons for the quiz administrator to:

1. Move to the next question.

1. View statistics for the current quiz session (e.g., number of participants, points, etc.).

- Ensure the component is styled in a fun and game-like manner to enhance the user experience.

**Comment by NoyMalka212** [comment]
want to work on this assignment.

**Comment by ChayaCodes** [comment]
Great, good luck @NoyMalka212 ! Keep me updated on your progress 🙂

**Comment by ChayaCodes** [comment]
@NoyMalka212, How it's going?

**Comment by ChayaCodes** [comment]
@NoyMalka212 I haven't heard from you and I don't know if you're still working on it, so for now I'm marking the issue as unassigned. If you're still working on it, let me know.

**Comment by ChayaCodes** [comment]
this duplicate with #26 issue
