### ISSUE TITLE
Add "Requirements" Page to Server and Update README

### ISSUE THREAD

**Issue by ChayaCodes** [ChayaCodes/trivia-quiz#8]
- Create a "Requirements" page on the server that details the necessary installations and dependencies for the project.

- Include information on how to set up the environment, install dependencies, and any other relevant setup instructions.

- Update the README file to include a section with installation instructions that link to or reference the "Requirements" page for a complete guide on setting up the project.

**Comment by ruth7873** [comment]
this is so important! I need it in order to begin!

**Comment by ChayaCodes** [comment]
Great, good luck @ruth7873 !

**Comment by ChayaCodes** [comment]
@ruth7873  Thanks for the update! Could you please explain what a virtual environment (venv) is and why it's necessary for the project?Thanks!

**Comment by ruth7873** [comment]
A virtual environment (venv) is an isolated Python environment where you can install packages and manage dependencies specific to your project. It ensures that different projects have their own dependencies and Python versions, avoiding conflicts that arise when packages are installed globally. Without a virtual environment, installing packages globally can lead to dependency clashes, system-level changes, or difficulty replicating the project setup for others. Using a virtual environment keeps your system Python clean and ensures your project is portable and self-contained.

**Comment by ChayaCodes** [comment]
@ruth7873 thanks!

**Comment by ChayaCodes** [comment]
Just need to update the installation information in the README.md file. Can you do that?

**Comment by ruth7873** [comment]
yes, now!
